FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-alpine3.11

# install all pre-requisites, these will be needed always
RUN apk update && apk add \
      openssl \
      opus-dev \
      opus-tools \
      ffmpeg \
      zip \
      bash

# download and install the TS3AudioBot in the specified version and flavour
RUN mkdir -p /opt/TS3AudioBot/build \
    && cd /opt/TS3AudioBot/build

COPY TS3AudioBot.sln /opt/TS3AudioBot/build/
COPY TS3AudioBot.ruleset /opt/TS3AudioBot/build/
COPY Directory.Build.targets /opt/TS3AudioBot/build/

COPY TS3AudioBot/ /opt/TS3AudioBot/build/TS3AudioBot/
COPY TSLib/ /opt/TS3AudioBot/build/TSLib/

ARG TS3_AUDIOBOT_BUILD_CONFIG="Debug"

WORKDIR /opt/TS3AudioBot/build/
RUN dotnet build --framework netcoreapp3.1 --configuration "$TS3_AUDIOBOT_BUILD_CONFIG" TS3AudioBot

RUN mv /opt/TS3AudioBot/build/TS3AudioBot/bin/"$TS3_AUDIOBOT_BUILD_CONFIG"/netcoreapp3.1/* /opt/TS3AudioBot/

# install and setup youtube-dl if configured
RUN apk update && apk add python3 youtube-dl

# add user to run under
RUN adduser --shell /bin/bash --uid 9999 --disabled-password ts3bot

# make data directory and chown it to the ts3bot user
RUN mkdir -p /data
RUN chown -R ts3bot:nogroup /data

# set user to ts3bot, we dont want to be root from now on
USER ts3bot

# set the work dir to data, so users can properly mount their config files to this dir with -v /host/path/to/data:/data
WORKDIR /data

CMD ["dotnet", "/opt/TS3AudioBot/TS3AudioBot.dll", "--non-interactive"]